### 异常概念
- 程序运行过程中发生的一些不正常事件
- 执行过程如出现异常事件，就可以生成一个异常类对象，该程序对象封装了异常事件的信息，并将其提交给java运行时系统，这个过程被称为抛出异常，不处理的话会直接导致程序直接中断。
- 设计良好地程序应该在程序异常发生时提供处理这些异常的方法，使得程序不会因为异常的发生而阻断或产生不可预见的结果
### 异常分类
- Error

|异常类型| 包括  | 来源   |  处理 |  
| -------|-------|-------|-------|  
|受查异常checkedException|Exception及其子类(不包括RuntimeException及其子类)|由代码控制能力之外的因素导致的运行时错误|必须要处理，否则通不过编译|
|非受查异常uncheckedException|Error和RuntimeException及其子类|RuntimeException一般代表变成错误|可以不用处理|
### 异常处理
  - 捕获：try-catch-finally
    - try 监控区域，执行可能产生异常的代码
    - catch 捕获、处理异常
    - finally 善后处理，无论是否发生异常，代码总能执行
  - 抛出：throw,throws
     - throw 手动抛出异常
     - throws 声明方法可能抛出的异常
 ### try-catch-finally
 - try 放要检测的java代码，可能会抛出异常，也可能正常执行
 - catch  java运行时系统接收try块中所抛出的对象时，会寻找能处理这一异常catch块来进行处理啊
 - finally 不管系统有咩有抛出异常都会去执行，一般用来释放资源。除了在之前执行了System.(exit(0))
 ### 实例
 ```java
  package Demo;
import java.util.InputMismatchException;
import java.util.Scanner;
public class ExceptionDemo1 {
	public static void main(String [] args) {
		testTryFinally("");
		System.out.println("请输入一个数字");
		Scanner input = new Scanner(System.in);
		int res=0;
		try {
		//System.exit(0);finally不再执行
		int number=input.nextInt();
		 res=10/number;
		}catch(Exception e) {
			System.out.println(e.getMessage());
		}
		/*catch(InputMismatchException e){
			System.out.println(e.getMessage());}
			//e.printStackTrace();
		catch(ArithmeticException e) {
			System.out.println(e.getMessage());
			//e.printStackTrace();
		}*/
		finally {
			//释放资源，关闭打开的文件，删除一些临时文件等
		System.out.println(res);
		}
	}
	
	
	public static void testTryFinally(String name) {
		try {
		System.out.println(name.length());
		}finally {
			System.out.println("end");
		}
		
		
	}
}

 ```
 ### throw和throws
 - throw用于手动抛出异常。作为程序员可以在任意位置手动抛出异常。
 - throws用于在方法上标识要暴露的异常。抛出的异常交由调用者处理。
 - 两者区别
   - throw用在方法内，后面跟上要抛出的异常类对象
   - throws修饰在方法上，告诉调用者此方法可能会抛出异常，后面跟上可能要抛出异常类名
 ### 实例
 ```java
     package Demo;

public class ExceptionDemo2 {
		public static void main(String [] args) {
			Bar bar=new Bar();
			try {
			  bar.enter(9);
			}catch(Exception e) {
				System.out.println("错误信息:"+e.getMessage());
			}
			System.out.println("end");
		}
}
class Bar{
	public void enter(int age) throws Exception
	{
		if(age<18) {
			//受查异常(必须捕获)和非受查异常   受查异常必须加throws
			//throw new IllegalArgumentException("年龄不合格");
			throw new Exception("年龄不合格");//受查异常
		}else {
			System.out.println("欢迎光临");
		}
	}
}
 ```
### 自定义异常
- 常见异常 
> RuntimeException，IOException
- 自定义异常
> Java提供的异常体系不可能遇见所有希望加以报告的错误
> 自定义异常类必须从已有的异常类继承
> 建立新的异常类型最简单的方法就是让编译器产生默认构造方法
> 对异常来说，最重要的部分就是他的类名
> 可以为异常类定义一个接受字符串参数的构造方法，字符串参数描述异常信息
### 实例 
```java
	package Demo;

public class ExceptionDemo3 {
		public static void main(String [] args) {
			Bar1 bar1=new Bar1();
			
			try {
				bar1.enter(15);
			}catch(AgeLessThanEighteenException e) {
				System.out.println("错误信息:"+e.getMessage());
			}
			
		}
}//自定义异常类
class AgeLessThanEighteenException extends Exception{
	private String message;//描述异常信息
	public AgeLessThanEighteenException(String message) {
		this.message=message;
	}
	public String getMessage(){
		return message;
	}
}
class Bar1{
	public void enter(int age) throws AgeLessThanEighteenException
	{
		if(age<18) {
			throw new AgeLessThanEighteenException("年龄不合格");
		}else {
			System.out.println("欢迎光临");
		}
	}
}
```
