### 异常概念
- 程序运行过程中发生的一些不正常事件
- 执行过程如出现异常事件，就可以生成一个异常类对象，该程序对象封装了异常事件的信息，并将其提交给java运行时系统，这个过程被称为抛出异常，不处理的话会直接导致程序直接中断。
- 设计良好地程序应该在程序异常发生时提供处理这些异常的方法，使得程序不会因为异常的发生而阻断或产生不可预见的结果
### 异常分类
- Error
- Exception
|异常类型| 包括  | 来源   |  处理 |
|-------|-------|-------|-------|
|受查异常checkedException|Exception及其子类(不包括RuntimeException及其子类)|由代码控制能力之外的因素导致的运行时错误|必须要处理，否则通不过编译|
|非受查异常uncheckedException|Error和RuntimeException及其子类|RuntimeException一般代表变成错误|可以不用处理|
### 异常处理
  - 捕获：try-catch-finally
    - try 监控区域，执行可能产生异常的代码
    - catch 捕获、处理异常
    - finally 善后处理，无论是否发生异常，代码总能执行
  - 抛出：throw,throws
     - throw 手动抛出异常
     - throws 声明方法可能抛出的异常
 ### try-catch-finally
 - try 放要检测的java代码，可能会抛出异常，也可能正常执行
 - catch  java运行时系统接收try块中所抛出的对象时，会寻找能处理这一异常catch块来进行处理啊
 - finally 不管系统有咩有抛出异常都会去执行，一般用来释放资源。除了在之前执行了System.(exit(0))
 ### 实例
 ```java
  package Demo;
import java.util.InputMismatchException;
import java.util.Scanner;
public class ExceptionDemo1 {
	public static void main(String [] args) {
		testTryFinally("");
		System.out.println("请输入一个数字");
		Scanner input = new Scanner(System.in);
		int res=0;
		try {
		//System.exit(0);finally不再执行
		int number=input.nextInt();
		 res=10/number;
		}catch(Exception e) {
			System.out.println(e.getMessage());
		}
		/*catch(InputMismatchException e){
			System.out.println(e.getMessage());}
			//e.printStackTrace();
		catch(ArithmeticException e) {
			System.out.println(e.getMessage());
			//e.printStackTrace();
		}*/
		finally {
			//释放资源，关闭打开的文件，删除一些临时文件等
		System.out.println(res);
		}
	}
	
	
	public static void testTryFinally(String name) {
		try {
		System.out.println(name.length());
		}finally {
			System.out.println("end");
		}
		
		
	}
}

 ```
